version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "docker"

[[transformers]]
name = "google-java-format"